#!/bin/bash

# Cross-LFS Bootscripts Tarball Package
#
DEST=$1
if [ -z "$DEST" ]; then
	DEST=/srv/ftp/pub/bootscripts
fi
cd /tmp
mkdir bootscripts
cd bootscripts
svn export http://svn.cross-lfs.org/svn/repos/bootscripts/trunk/standard bootscripts-cross-lfs
tar jcvf bootscripts-cross-lfs.tar.bz2 bootscripts-cross-lfs
mv bootscripts-cross-lfs.tar.bz2 $DEST
cd ..
rm -rf bootscripts
cd /tmp
mkdir bootscripts
cd bootscripts
svn export http://svn.cross-lfs.org/svn/repos/bootscripts/trunk/embedded clfs-embedded-bootscripts
tar jcvf clfs-embedded-bootscripts.tar.bz2 clfs-embedded-bootscripts
mv clfs-embedded-bootscripts.tar.bz2 $DEST
cd ..
rm -rf bootscripts

